config/routes.rb
Rails.application.routes.draw do
  resources :products
  root to: 'pages#front'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/product.rb
class Product < ActiveRecord::Base  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def front    
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  
  def index
    @products = Product.all    
  end

  def new
    @product = Product.new
  end

  def create
    @product = Product.new(product_params)
   
    if @product.save
      flash[:notice] = "Product created!"
      redirect_to root_path
    else
      render :new
    end
  end

  def show
    @product = Product.find(params[:id])
  end
 

  private

  def product_params
    params.require(:product).permit!
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Bazaar|Create Your Store
    %meta{:charset => "utf-8"}/
    %meta{:content => "width=device-width, initial-scale=1, shrink-to-fit=no", :name => "viewport"}/
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    %header
      = render 'shared/header'
    = yield

app/views/pages/front.html.haml
%main.container{:role => "main"}
  .starter-template
    %h1 Bootstrap starter template
    %p.lead
      Use this document as a way to quickly start any new project.
      %br/
      All you get is this text and a mostly barebones HTML document.

app/views/products/_product.html.haml
.col-md-4
  .card{:style => "width: 18rem;"}
    %img.card-img-top.img-fluid{:alt => "Card image cap", :src => "#{product.image_url}"}
    .card-body
      %p.card-text= product.name

app/views/products/index.html.haml
.container
  .row
    .col-md-3
      %h3
        Products Page
  .row    
    = render @products

app/views/shared/_header.html.haml
%nav.navbar.navbar-expand-lg.navbar-light.bg-light
  .navbar-brand
    = link_to "Bazaar", root_path
  %button.navbar-toggler{"aria-controls" => "navbarSupportedContent", "aria-expanded" => "false", "aria-label" => "Toggle navigation", "data-target" => "#navbarSupportedContent", "data-toggle" => "collapse", :type => "button"}
    %span.navbar-toggler-icon
  #navbarSupportedContent.collapse.navbar-collapse
    %ul.navbar-nav.mr-auto      
      %li.nav-item
        = link_to 'Products', products_path, class: 'nav-link'
      %li.nav-item.dropdown
        %a#navbarDropdown.nav-link.dropdown-toggle{"aria-expanded" => "false", "aria-haspopup" => "true", "data-toggle" => "dropdown", :href => "#", :role => "button"}
          Dropdown
        .dropdown-menu{"aria-labelledby" => "navbarDropdown"}
          %a.dropdown-item{:href => "#"} Action
          %a.dropdown-item{:href => "#"} Another action
          .dropdown-divider
          %a.dropdown-item{:href => "#"} Something else here      
    %form.form-inline.my-2.my-lg-0
      %input.form-control.mr-sm-2{"aria-label" => "Search", :placeholder => "Search", :type => "search"}/
      %button.btn.btn-outline-success.my-2.my-sm-0{:type => "submit"} Search